### ISSUE TITLE
无法做失去焦点校验json规则是否正确，json如果输入错误，则无法获取到~

### ISSUE THREAD

**Issue by storyNan** [guyue88/json-editor-vue3#1]

**Comment by Kitesource** [comment]
> ```
> <JsonEditorVue class="editor" v-model="data" @blur="validate" />
> const validate = async (editor) => {
>       const res = await editor.validate();
>       console.log(res);
>     };
> ```
> 
> 增加 blur 事件，可以在事件回调中使用editor 实例进行校验，校验结果为空则表示没有错误

blur 监听不到诶

**Comment by guyue88** [comment]
> > ```
> > <JsonEditorVue class="editor" v-model="data" @blur="validate" />
> > const validate = async (editor) => {
> >       const res = await editor.validate();
> >       console.log(res);
> >     };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 增加 blur 事件，可以在事件回调中使用editor 实例进行校验，校验结果为空则表示没有错误
> 
> blur 监听不到诶

代码贴一下

**Comment by Kitesource** [comment]
> > > ```
> > > <JsonEditorVue class="editor" v-model="data" @blur="validate" />
> > > const validate = async (editor) => {
> > >       const res = await editor.validate();
> > >       console.log(res);
> > >     };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 增加 blur 事件，可以在事件回调中使用editor 实例进行校验，校验结果为空则表示没有错误
> > 
> > 
> > blur 监听不到诶
> 
> 代码贴一下

我的场景是在dialog使用改插件，blur监听无效

**Comment by Kitesource** [comment]
<el-button @click="dialogVisible = true">show</el-button>
    <el-dialog v-model="dialogVisible" title="Tips" width="600px">
      <el-form :model="form">
        <el-form-item label="json" prop="json">
          <json-editor-vue
            class="json-editor"
            v-model="form.json"
            @blur="validate2"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="dialogVisible = false">Cancel</el-button>
          <el-button type="primary" @click="dialogVisible = false"
            >Confirm</el-button
          >
        </span>
      </template>
    </el-dialog>

const validate2 = async (editor) => {
  const res = await editor.validate()
  console.log('validate2', res)
}

**Comment by Kitesource** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/70793114/164587362-bfac5e30-a7cd-4f58-8c47-4a6f022d4d19.png">

**Comment by guyue88** [comment]
应该是dialog拦截了blur事件吧

**Comment by Kitesource** [comment]
> 大师，这个怎么解决呀o(╥﹏╥)o

**Comment by Kitesource** [comment]
插件会有这个Sourcemap for "/Users/fuzhouchen/Desktop/projects/onetest-fe/node_modules/jsoneditor/dist/jsoneditor.min.js" points to missing source files ？？
