### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by jzfai** [guyue88/json-editor-vue3#10]
Sourcemap for "D:/github/low-code-generator/node_modules/.pnpm/jsoneditor@9.9.2/node_modules/jsoneditor/dist/jsoneditor.min.js" points to missing source files
![image](https://user-images.githubusercontent.com/35098590/218363908-4222fd96-141e-49a2-9cb1-925994ad6be0.png)

**Comment by guyue88** [comment]
> Sourcemap for "D:/github/low-code-generator/node_modules/.pnpm/jsoneditor@9.9.2/node_modules/jsoneditor/dist/jsoneditor.min.js" points to missing source files ![image](https://user-images.githubusercontent.com/35098590/218363908-4222fd96-141e-49a2-9cb1-925994ad6be0.png)

你可能需要看一下，你是否安装jsoneditor成功了
