### ISSUE TITLE
编辑器好像不支持readonly和disabled

### ISSUE THREAD

**Issue by chuwarriors** [guyue88/json-editor-vue3#11]
在组件上使用readonly和disabled不生效，并且文档参数中没有看到相关属性，请问是否提供类似功能？ @guyue88

**Comment by guyue88** [comment]
不支持哦

**Comment by coderxiao24** [comment]
![Image](https://github.com/user-attachments/assets/d9e1373d-2ecd-4731-8705-5884a65e7bca)
