### ISSUE TITLE
vue3+vite引入异常：Uncaught TypeError: window.Vue.component is not a function

### ISSUE THREAD

**Issue by cjmld5** [guyue88/json-editor-vue3#12]
![image](https://github.com/guyue88/json-editor-vue3/assets/6902006/05db7ed7-0710-4410-9fc5-6051fee1191f)
vue3+vite按文档中的n局部引入方式，判断出现了用vue2方式的注册导致插件加载失败。
Uncaught TypeError: window.Vue.component is not a function

**Comment by magic-luoqiang** [comment]
@cjmld5 将去除vue2的这种注册方式

**Comment by guyue88** [comment]
@cjmld5 将在v1.1.1版本中去除vue2的这种注册方式
