### ISSUE TITLE
为什么只有事件没有方法

### ISSUE THREAD

**Issue by hw-barry** [guyue88/json-editor-vue3#14]
可以把方法暴露出来吗

**Comment by magic-luoqiang** [comment]
@hw-barry 实例没有办法透传上去吧，在暴露出来的回调里面都会有实例，你可以在事件回调里面通过editor实例调用对应方法

**Comment by guyue88** [comment]
@hw-barry 实例没有办法透传上去，在暴露出来的回调里面都会有实例，你可以在事件回调里面通过editor实例调用对应方法
