### ISSUE TITLE
vite用引用报错

### ISSUE THREAD

**Issue by Bleachtred** [guyue88/json-editor-vue3#15]
![image](https://github.com/guyue88/json-editor-vue3/assets/39073073/ec452844-3e89-4680-b019-582ed342eb8d)

参考 [issue #4](https://github.com/guyue88/json-editor-vue3/issues/4) 修改后依然无法正常使用

![image](https://github.com/guyue88/json-editor-vue3/assets/39073073/168ace14-62d3-447b-8a74-2fceab8e2884)

**Comment by magic-luoqiang** [comment]
@Bleachtred 在入口文件引入，不是页面文件哈

**Comment by guyue88** [comment]
@Bleachtred 在入口文件引入

**Comment by magic-luoqiang** [comment]
@Bleachtred 你把项目文件发我看一下

**Comment by guyue88** [comment]
@Bleachtred 你把项目文件发我看一下

**Comment by Bleachtred** [comment]
我们是内部文件 只能截图截一点 就是在回复里的那些。我的处理方式是和这里是一模一样的  更换Json组件 · 742b852 · flowlong/flowlong-designer - Gitee.com



出淤泥而不染，濯清涟而不妖。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月14日 14:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [guyue88/json-editor-vue3] vite用引用报错 (Issue #15) |

@Bleachtred 你把项目文件发我看一下
