### ISSUE TITLE
在 view 模式下关键字搜索速度优化方法

### ISSUE THREAD

**Issue by GuangZ96** [guyue88/json-editor-vue3#18]
若 modelValue 为一个过万行的 json 对象，在切换到 view 模式下在右上角搜索关键字时花费时间过长，出现明显卡顿（大约在6、7秒），用户体验较差，求优化方法

另我 language 配置了中文后，搜索完关键字后搜索框旁还是提示"xx results"，这个又该如何解决？

**Comment by magic-luoqiang** [comment]
这优化，我也不会啊

**Comment by guyue88** [comment]
要优化这个的话，我也没有什么好想法 @GuangZ96

**Comment by GuangZ96** [comment]
> 要优化这个的话，我也没有什么好想法 @GuangZ96

或者我可以怎样去监听每当我在搜索框里输入完值之后，先在界面上显示一个 loading 的 gif，等定位到关键字位置后再结束 loading ?（其实就是怎样监听搜索框的值改变了以及关键字定位完成这两个动作 @guyue88

**Comment by guyue88** [comment]
> > 要优化这个的话，我也没有什么好想法 @GuangZ96
> 
> 或者我可以怎样去监听每当我在搜索框里输入完值之后，先在界面上显示一个 loading 的 gif，等定位到关键字位置后再结束 loading ?（其实就是怎样监听搜索框的值改变了以及关键字定位完成这两个动作 @guyue88

应该是不支持的，或者你可以看看这个文档里面有没有 https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options

**Comment by guyue88** [comment]
> > 要优化这个的话，我也没有什么好想法 @GuangZ96
> 
> 或者我可以怎样去监听每当我在搜索框里输入完值之后，先在界面上显示一个 loading 的 gif，等定位到关键字位置后再结束 loading ?（其实就是怎样监听搜索框的值改变了以及关键字定位完成这两个动作 @guyue88

应该是不支持的，或者你可以看看这个文档里面有没有 https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options

**Comment by GuangZ96** [comment]
> > > 要优化这个的话，我也没有什么好想法 @GuangZ96
> > 
> > 
> > 或者我可以怎样去监听每当我在搜索框里输入完值之后，先在界面上显示一个 loading 的 gif，等定位到关键字位置后再结束 loading ?（其实就是怎样监听搜索框的值改变了以及关键字定位完成这两个动作 @guyue88
> 
> 应该是不支持的，或者你可以看看这个文档里面有没有 https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options

好的，我会去看看的
