### ISSUE TITLE
中文的language怎么设置

### ISSUE THREAD

**Issue by xibaoning** [guyue88/json-editor-vue3#19]
如题

**Comment by guyue88** [comment]
@xibaoning 
![image](https://github.com/user-attachments/assets/f71c901f-5826-458a-af64-aa24b85e45a7)

**Comment by xibaoning** [comment]
<json-editor-vue :modeList="['code']" language="zh-CN" v-model="signalcontent"
                    :options="{ mainMenuBar: false }" style="height: 660px" />
设置后状态栏仍然是英文呢：
Ln:29Col:25131characters selected

**Comment by luoqiang-wm** [comment]
@xibaoning 应该需要加载一下翻译文件，你可以看看文档

**Comment by guyue88** [comment]
@xibaoning 应该需要加载一下翻译文件，你可以看看文档
