### ISSUE TITLE
你好，使用中发现空对象任意地方回车无效

### ISSUE THREAD

**Issue by hu5871** [guyue88/json-editor-vue3#5]
![image](https://user-images.githubusercontent.com/68421705/174434197-df4865a9-b62f-4b5e-a616-71b7062180ec.png)

**Comment by hu5871** [comment]
造成的原因可能是每次自动格式化

**Comment by guyue88** [comment]
开启格式化，确实没有办法保持修改后的格式，可以将格式化关闭试试？
