### ISSUE TITLE
关于在Code模式下，在未全屏时候，超出了组件显示行数量，进入全屏模式后，不会自适应拉伸。

### ISSUE THREAD

**Issue by icylles** [guyue88/json-editor-vue3#8]
关于在Code模式下，在未全屏时候，超出了组件显示行数量，进入全屏模式后，不会自适应拉伸。
在全屏状态下，切换展示模式，可以恢复全屏状态下的展示效果。
如图：
未全屏下，总数量为17行，组件内展示8行。
![1675221074939](https://user-images.githubusercontent.com/83400767/215936619-9dac2d8c-8ad9-440a-922d-d7f94123f8b2.png)
进入全屏后，展示10行，未能在展现全屏下应有的效果。
![1675221085487](https://user-images.githubusercontent.com/83400767/215936835-1b9c0a2a-fcdc-4a38-8d1b-2523ddf013f6.png)
![1675221093237](https://user-images.githubusercontent.com/83400767/215936869-72244e32-a9f1-4698-86e7-80cb2a9df798.png)
切换显示模式，换到Tree后，显示正常。
![1675221105822](https://user-images.githubusercontent.com/83400767/215936920-20bd0657-e3ac-4960-bdb1-4af4c2a4a3a1.png)
在切换回Code模式，显示正常。
![1675221113700](https://user-images.githubusercontent.com/83400767/215936945-5d10d94e-ca8e-4454-938c-fc9424d99ac0.png)

**Comment by guyue88** [comment]
@icylles 兄弟，我看了一下这个问题，原因在于jsoneditor本身在高度变化时没有做适配，尝试修复一下了一下，但是没有解决，可能需要jsoneditor本身去解决了！

**Comment by guyue88** [comment]
@icylles 已在1.0.8版本解决
